version: "3.7"
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pg-dataset:/var/lib/postgresql/lyme/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lyme.in
      PGADMIN_DEFAULT_PASSWORD: 123456s
    ports:
      - "5050:80"

volumes:
  pg-dataset:
